# Configurations
title:            SKKU COMEDU NLP CS224n
longtitle:        SKKU COMEDU NLP CS224n
author:           SKKU COMEDU
email:            jasonchoi3@g.skku.edu
description: >
  성균관대학교 컴퓨터교육과 학생들의 2022년 겨울 자연어 처리 스터디 입니다. 최신 버전 (2021 Winter)로 진행하였습니다.

version:          1.0
gitbook_version:  3.2.3

url:              'https://skku-comedu-nlp.github.io/cs224n'
baseurl:          '/'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji
